export declare const container,
  title,
  date,
  header,
  statusBox,
  ringImg,
  subTitle,
  infoBox,
  infoIcon,
  infoITitle,
  infoValue,
  remainDayText,
  remainDayCount,
  remainDayContent,
  detailBtn,
  renevalBtn,
  btnBox,
  renevalContainer,
  detailContainer,
  informationBox,
  informationContainer,
  editIcon: string;
