export declare const container,
  title,
  date,
  header,
  statusBox,
  ringImg,
  renevalSubTitle,
  reaminSubTitle,
  renevalSubTitleServis,
  infoBox,
  infoIcon,
  infoITitle,
  infoValue,
  remainDayText,
  remainDayCount,
  remainDayContent,
  detailBtn,
  renevalBtn,
  btnBox,
  renevalContainer,
  detailContainer,
  informationBox,
  informationContainer,
  editIcon,
  renevalInfoValue,
  renevalInfoTitle,
  divider,
  payBtn: string;
